apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "scanner.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ template "scanner.name" . }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ template "scanner.name" . }}"
        release: "{{ .Release.Name }}"
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- end }}
    spec:
      serviceAccountName: {{ template "scanner.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      {{- end }}
      containers:
      - name: scanner
        image: {{ .Values.scanner.registry }}/{{ .Values.scanner.repository }}:{{ .Values.scanner.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --clair-addr=https://{{ template "clair.name" . }}.{{ .Release.Namespace }}.svc:6060
        - --clair-cert-dir=/var/run/secrets/clair
        - --enable-analytics={{ .Values.enableAnalytics }}
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
{{- if .Values.clair.enabled }}
        - mountPath: /var/run/secrets/clair
          name: clair-client-cert
{{- end }}
      volumes:
      - name: serving-cert
        secret:
          secretName: {{ template "scanner.fullname" . }}-server-cert
{{- if .Values.clair.enabled }}
      - name: clair-client-cert
        secret:
          secretName: {{ template "clair.fullname" . }}-client-cert
{{- end }}
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
{{- end -}}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end -}}
