{{- $ca := genCA "https-practice-ca" 3650 }}
{{- $cn := include "https-book-server.fullname" . -}}
{{- $altName := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $server := genSignedCert "shudipta.com" (list "127.0.0.1" "192.168.99.100") (list "localhost" $altName) 365 $ca }}
{{- $client := genSignedCert "shudipta.com" (list "127.0.0.1" "192.168.99.100") (list "localhost" $altName) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "https-book-server.fullname" . }}-secret
  namespace: {{ .Release.Namespace}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "https-book-server.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  server.crt: {{ b64enc $server.Cert }}
  server.key: {{ b64enc $server.Key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "https-book-server.fullname" . }}-client-secret
  namespace: {{ .Release.Namespace}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "https-book-server.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  client.crt: {{ b64enc $client.Cert }}
  client.key: {{ b64enc $client.Key }}