// Code generated by go-enum
// DO NOT EDIT!

package types

import (
	"fmt"
	"strings"
)

const (
	// SeverityDefcon1 is a Severity of type Defcon1
	SeverityDefcon1 Severity = iota
	// SeverityCritical is a Severity of type Critical
	SeverityCritical
	// SeverityHigh is a Severity of type High
	SeverityHigh
	// SeverityMedium is a Severity of type Medium
	SeverityMedium
	// SeverityLow is a Severity of type Low
	SeverityLow
	// SeverityNegligible is a Severity of type Negligible
	SeverityNegligible
	// SeverityUnknown is a Severity of type Unknown
	SeverityUnknown
)

const _SeverityName = "Defcon1CriticalHighMediumLowNegligibleUnknown"

var _SeverityMap = map[Severity]string{
	0: _SeverityName[0:7],
	1: _SeverityName[7:15],
	2: _SeverityName[15:19],
	3: _SeverityName[19:25],
	4: _SeverityName[25:28],
	5: _SeverityName[28:38],
	6: _SeverityName[38:45],
}

func (i Severity) String() string {
	if str, ok := _SeverityMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Severity(%d)", i)
}

var _SeverityValue = map[string]Severity{
	_SeverityName[0:7]:                    0,
	strings.ToLower(_SeverityName[0:7]):   0,
	_SeverityName[7:15]:                   1,
	strings.ToLower(_SeverityName[7:15]):  1,
	_SeverityName[15:19]:                  2,
	strings.ToLower(_SeverityName[15:19]): 2,
	_SeverityName[19:25]:                  3,
	strings.ToLower(_SeverityName[19:25]): 3,
	_SeverityName[25:28]:                  4,
	strings.ToLower(_SeverityName[25:28]): 4,
	_SeverityName[28:38]:                  5,
	strings.ToLower(_SeverityName[28:38]): 5,
	_SeverityName[38:45]:                  6,
	strings.ToLower(_SeverityName[38:45]): 6,
}

// ParseSeverity attempts to convert a string to a Severity
func ParseSeverity(name string) (Severity, error) {
	if x, ok := _SeverityValue[name]; ok {
		return Severity(x), nil
	}
	return Severity(0), fmt.Errorf("%s is not a valid Severity", name)
}

// Set implements the Golang flag.Value interface func
func (x *Severity) Set(val string) error {
	v, err := ParseSeverity(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func
func (x *Severity) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface
func (x *Severity) Type() string {
	return "Severity"
}
