apiVersion: v1
kind: Service
metadata:
  name: {{ template "clair.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "clair.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: clair-api
    port: {{ .Values.service.externalApiPort }}
    targetPort: {{ .Values.service.internalApiPort }}
    protocol: TCP
    name: "{{ .Values.service.name }}-api"
  - name: clair-health
    port: {{ .Values.service.externalHealthPort }}
    targetPort: {{ .Values.service.internalHealthPort }}
    protocol: TCP
    name: "{{ .Values.service.name }}-health"
  selector:
    app: {{ template "clair.fullname" . }}
